import turtle

def write_initials():

    #Brads Configuration
    window = turtle.Screen()
    window.bgcolor("blue")
    brad = turtle.Turtle()
    brad.shape("arrow")
    brad.color("cyan")
    brad.speed(1)
    brad.pensize(10)

    #Brads Movement for my initials
    brad.hideturtle()
    brad.left(90)
    brad.penup()
    brad.backward(400)
    brad.left(90)
    brad.forward(300)
    brad.right(90)
    brad.showturtle()
    brad.pendown()
    brad.forward(500)
    brad.right(135)
    brad.forward(300)
    brad.left(90)
    brad.forward(300)
    brad.right(135)
    brad.forward(500)
    brad.penup()
    brad.left(90)
    brad.forward(100)
    brad.left(90)
    brad.pendown()
    brad.forward(500)
    brad.right(180)
    brad.forward(250)
    brad.left(135)
    brad.forward(340)
    brad.left(180)
    brad.forward(340)
    brad.left(90)
    brad.forward(340)
    brad.penup()
    brad.left(45)
    brad.forward(200)
    brad.left(90)
    brad.forward(50)
    brad.pendown()
    brad.forward(5)
    brad.penup()
    brad.forward(50)
    brad.pendown()
    brad.forward(370)
    brad.hideturtle()
    

#Execute the write_initials function
write_initials()
